vmware-tanzu/cloud-native-security-inspector

- src/go.mod
- src/pkg/policy/network/enforcer_test.go
Update the import URL in the unit test file. Update the go.mod file.
> Update the import URL in unit test

- src/cmd/inspector/main.go
- src/config/samples/goharbor_v1alpha1_inspectionpolicy.yaml
- src/go.mod
- src/pkg/data/consumers/es/client.go
- src/pkg/data/consumers/es/exporter.go
- src/pkg/inspection/controller.go
Update the sample inspectionpolicy.yaml and the log in ElasticSearch exporter.
> Update the config files and the log in ElasticSearch

- .github/workflows/deploy-to-kind.yml
- .github/workflows/main.yml
- src/Makefile
Change the go verison to 1.19 in github action
> change go version in github action

- src/pkg/data/consumers/es/client.go
- src/pkg/data/consumers/es/exporter.go
- src/pkg/data/consumers/opensearch/exporter.go
- src/pkg/inspection/controller.go
- src/pkg/inspection/kubebench/common.go
Format the log and remove unused codes.
> Format the log

- TUTORIAL.md
> tutorial part1: add how to set up K8s and deploy CNSI

- src/pkg/data/consumers/es/exporter.go
Fix index mapping in ElasticSearch
> Update index mapping for ElasticSearch

- TUTORIAL.md
> tutorial part2: add content about creating setting and policy

- src/cmd/riskmanager/main.go
- src/pkg/data/consumers/es/client.go
- src/pkg/data/consumers/opensearch/client.go
- src/pkg/inspection/controller.go
- src/pkg/inspection/kubebench/controller.go
> fix the key==nil issue in the logs

- src/frontend/src/assets/i18n/en.json
- src/frontend/src/assets/i18n/zh_CN.json
> fix the non-native expression

- src/controllers/inspectionpolicy_controller.go
The issue is that:
If we create a policyA in workspace namespace ws1, it will create SA(in ws1), role, and cluster role binding, this is fine.
When we delete policyA, it will not delete above 3 things.
Now we create policyA again in workspace namespace ws2. Then it will create a SA in ws2,  but it will not change the ClusterRoleBinding to bind the role to the new SA in ws2.
Fix:
If the new workspace is not equal to the old one, we should update the CRB to point to the new ServiceAccount.
Test:
1. Install policy A with workspace setting to "ws1"
2. Verified everything works properly. Notice the CRB points to a SA in ws1, which is expected.
```
01:26:26 root@example ~ → kd clusterrolebinding cnsi-inspector-rolebinding
Name: …
```
> fix the issue of workspace change

- src/Dockerfile.kubebench
- src/Dockerfile.manager.local
- src/Makefile
- src/api/v1alpha1/inspectionpolicy_types.go
- src/api/v1alpha1/zz_generated.deepcopy.go
- src/cmd/kubebench/main.go
- src/config/crd/bases/goharbor.goharbor.io_inspectionpolicies.yaml
- src/config/rbac/role.yaml
- src/controllers/inspectionpolicy_controller.go
- src/lib/log/entry.go
- src/lib/log/formatter.go
- src/lib/log/level.go
- src/lib/log/logger.go
- src/lib/log/logger_test.go
- src/lib/log/textformatter.go
- src/main.go
- src/pkg/data/consumers/assessmentreport_document.go
- src/pkg/data/consumers/es/exporter.go
- src/pkg/data/consumers/opensearch/exporter.go
- src/pkg/data/consumers/opensearch/exporter_test.go
- src/pkg/inspection/kubebench/common.go
- src/pkg/inspection/kubebench/controller.go
- src/pkg/inspection/kubebench/util.go
1. Update the kubebench cronjob CR. 
(1)Will create multiple cronjobs corresponding to the node count and schedule them to every node in the cluster.
(2)Make sure related host paths are mounted to cronjobs. 
2. Change the base image of kubebench scanner to ubuntu:22.04
Contexts:
#88  #87 #94
> Fix: fix issue 87

- src/frontend/node-server.js
- src/frontend/src/app/app.module.ts
- src/frontend/src/app/view/assements/kube-bench-report-list/kube-bench-report-list.component.css
- src/frontend/src/app/view/assements/kube-bench-report-list/kube-bench-report-list.component.html
- src/frontend/src/app/view/assements/kube-bench-report-list/kube-bench-report-list.component.less
- src/frontend/src/app/view/assements/kube-bench-report-list/kube-bench-report-list.component.ts
- src/frontend/src/app/view/assements/risk-report-detail/risk-report-detail.component.html
- src/frontend/src/app/view/assements/risk-report-view/risk-report-view.component.ts
- src/frontend/src/app/view/setting/harbor-setting-page/harbor-setting-page.component.ts
- src/frontend/src/app/view/setting/setting.component.html
- src/frontend/src/app/view/setting/setting.component.ts
- src/frontend/src/app/view/summary/cluster/cluster.component.html
1. Update kube bench report
2.Add restrictions on deleting settings
> Update related content of risk and kube portal

- PULL_REQUEST_TEMPLATE.md
> add pr template

- src/controllers/inspectionpolicy_controller.go
Fixes ISSUE #96
What will be the pain point if you don't make this change?
batchv1alpha will be abandoned by k8s 1.25
```
W1221 04:21:29.907734       1 warnings.go:70] batch/v1beta1 CronJob is deprecated in v1.21+, unavailable in v1.25+; use batch/v1 CronJob
W1221 04:29:39.917119       1 warnings.go:70] batch/v1beta1 CronJob is deprecated in v1.21+, unavailable in v1.25+; use batch/v1 CronJob
W1221 04:36:01.918059       1 warnings.go:70] batch/v1beta1 CronJob is deprecated in v1.21+, unavailable in v1.25+; use batch/v1 CronJob
```
The logs are gone.
> use batchv1 to create the cronjobs

- src/cmd/inspector/main.go
- src/cmd/kubebench/main.go
- src/cmd/riskmanager/main.go
- src/controllers/assessmentreport_controller.go
- src/controllers/inspectionpolicy_controller.go
- src/controllers/setting_controller.go
- src/go.mod
- src/go.sum
- src/main.go
- src/pkg/data/consumers/es/client.go
- src/pkg/data/consumers/es/exporter.go
- src/pkg/data/consumers/opensearch/client.go
- src/pkg/data/consumers/opensearch/exporter.go
- src/pkg/data/consumers/opensearch/exporter_test.go
- src/pkg/data/providers/harbor/adapter.go
- src/pkg/inspection/controller.go
- src/pkg/inspection/data/eval.go
- src/pkg/inspection/data/resources.go
- src/pkg/inspection/kubebench/common.go
- src/pkg/inspection/kubebench/controller.go
- src/pkg/inspection/kubebench/util.go
- src/pkg/inspection/riskmanager/client.go
- src/pkg/inspection/riskmanager/controller.go
- src/pkg/inspection/riskmanager/server.go
- src/pkg/inspection/scanner.go
- src/pkg/policy/factory.go
- src/pkg/runtime/grpool/pool.go
Fixes ISSUE #117
What will be the pain point if you don't make this change?
This change unifies the logger everywhere, including the `fmt.println` ways.
Also improves the code quality
This change does not change any functionality.
Will do post-submit test after check-in.
> unify log and improve code quality

- src/frontend/node-server.js
- src/frontend/src/app/view/assements/kube-bench-report-list/kube-bench-report-list.component.css
- src/frontend/src/app/view/assements/kube-bench-report-list/kube-bench-report-list.component.html
- src/frontend/src/app/view/assements/kube-bench-report-list/kube-bench-report-list.component.less
- src/frontend/src/app/view/assements/kube-bench-report-list/kube-bench-report-list.component.ts
1.Integrate kubebench report chart legend
> Integrate kubebench report chart legend

- src/frontend/node-server.js
- src/frontend/src/app/view/assements/report-view/report-view.component.ts
- src/frontend/src/app/view/assements/risk-report-view/risk-report-view.component.ts
1.Set scanner report chart width to automatic calculation
> Set scanner report chart width to automatic calculation

- src/Makefile
Update makefile to generate the yaml files using "gen-and-apply-crd"
> Update Makefile to generate yaml files with a command

- src/frontend/node-server.js
- src/frontend/src/app/view/assements/report-view/report-view.component.ts
- src/frontend/src/app/view/assements/risk-report-detail/risk-report-detail.component.css
- src/frontend/src/app/view/assements/risk-report-detail/risk-report-detail.component.less
- src/frontend/src/app/view/assements/risk-report-detail/risk-report-detail.component.ts
- src/frontend/src/app/view/assements/risk-report-view/risk-report-view.component.css
- src/frontend/src/app/view/assements/risk-report-view/risk-report-view.component.html
- src/frontend/src/app/view/assements/risk-report-view/risk-report-view.component.less
- src/frontend/src/app/view/assements/risk-report-view/risk-report-view.component.ts
- src/frontend/src/app/view/insight/workload-page/workload-page.component.css
- src/frontend/src/app/view/insight/workload-page/workload-page.component.html
- src/frontend/src/app/view/insight/workload-page/workload-page.component.less
- src/frontend/src/app/view/insight/workload-page/workload-page.component.ts
1.Image scanning report Line chart data aggregation problem solving.
2.The image, risk, and workload detail pages add drag and drop functions and fix hidden problems in drag and drop.
3.Risk scanning report line chart xAxis problem display order adjustment
4.The data in the detail in the risk scanning report detail page is hidden after exceeding the width
> Portal 2023 fixed

- src/frontend/node-server.js
- src/frontend/src/app/view/assements/risk-report-detail/risk-report-detail.component.ts
- src/frontend/src/app/view/assements/risk-report-view/risk-report-view.component.html
- src/frontend/src/app/view/assements/risk-report-view/risk-report-view.component.ts
1.The detail chart in the risk scanning report detail page cannot be displayed normally
> The detail chart in the risk scanning report detail page cannot be displayed normally

- src/frontend/node-server.js
- src/frontend/src/app/view/assements/kube-bench-report-list/kube-bench-report-list.component.ts
- src/frontend/src/app/view/assements/risk-report-view/risk-report-view.component.ts
1.Make changes to the report according to the policy situation
> Make changes to the report according to the policy situation

- src/frontend/node-server.js
- src/frontend/src/app/view/assements/risk-report-detail/risk-report-detail.component.html
- src/frontend/src/app/view/assements/risk-report-detail/risk-report-detail.component.ts
1.The risk scanning report detail page pods list expands and merges, resulting in chart loss problem solved
> The risk scanning report detail page pods list expands and merges, resulting in chart loss problem solved

- src/frontend/README.md
- src/frontend/node-server.js
- src/frontend/proxy.config.json
> Updated Frontend Developer Guide For Cloud Native Security Inspector

- src/pkg/inspection/data/eval.go
> improve risk reason msg: add 3 spaces

- src/go.mod
- src/go.sum
- src/test/e2e/e2e_test.go
- src/test/e2e/inspectionpolicy/inspectionpolicy.yaml
- src/test/e2e/inspectionpolicy/register.go
- src/test/e2e/inspectionpolicy_test.go
- src/test/e2e/setting/register.go
- src/test/e2e/setting/setting.yaml
- src/test/e2e/setting_test.go
- src/tools/installation/yaml/crd.yaml
Set up the E2E test for CNSI using e2e-framework. Currently, only inspection policies and settings are covered. Will complete all the E2E test cases in the future.
> Commit the initial version of E2E test

- docs/design/template.md
Signed-off-by: Chen Jing <616922548@qq.com>
This change has only document change.
I'm jingch@vmware.com, I create this pr to go through the CLA process, get some screenshots and put them in another document.
> Add the design doc template

- src/frontend/src/app/service/harbor-model-type.ts
- src/frontend/src/app/view/assements/risk-report-view/risk-report-view.component.ts
- src/frontend/src/app/view/setting/setting.component.ts
> develop-0.3 cypress fixed

- docs/GOVERNOR.md
> Fix typos and format

- src/frontend/src/app/view/assements/kube-bench-report-list/kube-bench-report-list.component.html
- src/frontend/src/app/view/assements/kube-bench-report-list/kube-bench-report-list.component.ts
- src/frontend/src/app/view/assements/report-view-detail/report-view-detail.component.html
- src/frontend/src/app/view/assements/report-view/report-view.component.html
- src/frontend/src/app/view/assements/report-view/report-view.component.ts
- src/frontend/src/app/view/assements/risk-report-view/risk-report-view.component.html
- src/frontend/src/app/view/assements/risk-report-view/risk-report-view.component.ts
- src/frontend/src/app/view/home/home.component.ts
- src/frontend/src/app/view/insight/cluster-page/cluster-page.component.html
- src/frontend/src/app/view/insight/cluster-page/cluster-page.component.ts
- src/frontend/src/app/view/insight/namespace-page/namespace-page.component.ts
- src/frontend/src/app/view/insight/workload-page/workload-page.component.ts
- src/frontend/src/app/view/policy/policy-setting-page/policy-setting-page.component.html
- src/frontend/src/app/view/policy/policy-setting-page/policy-setting-page.component.spec.ts
- src/frontend/src/app/view/policy/policy-setting-page/policy-setting-page.component.ts
- src/frontend/src/app/view/policy/policy.component.ts
- src/frontend/src/app/view/summary/namespace/namespace.component.spec.ts
- src/frontend/src/app/view/summary/namespace/namespace.component.ts
1.Adjust the portal according to the new policy format
2.Replace the insight data source from cr to open search
3.Update the index used before
> Update the open search index in the portal, verify and modify

- src/tools/installation/charts/cnsi/README.md
- src/tools/installation/charts/cnsi/templates/NOTES.txt
Ensure users can install CNSI by using the helm chart stored in Harbor. Update the doc for using Helm.
> Update doc for helm

- src/pkg/inspectors/riskmanager/cmd/main.go
- src/pkg/inspectors/riskmanager/data/resources.go
- src/pkg/inspectors/riskmanager/server.go
> # fix issues 173

- docs/GOVERNOR.md
Fixes ISSUE [BEGONIA-87]
-- Edited md page for Governor and added setup steps with Prerequisites
> [BEGONIA-87] Add Setup steps in Markdown page of Governor

- CONTRIBUTING.md
- docs/EXTEND-NARROWS.md
This change add docs to tell the users how to:
1. Extend scanners
2. Extend consumers
3. Add test cases and run test
> add document about how to extend Narrows 0.3

- cnsi-portal/node-server.js
> portal security fixed

- cnsi-portal/scripts/cloud-native-security-inspector-portal.yaml
Corrected the image corresponding to portal in 0.3.1
> Corrected the image corresponding to portal in 0.3.1

- cnsi-portal/src/app/view/assements/report-view-detail/report-view-detail.component.html
Update the content of some portals corresponding to vac.
> Update the content of some portals corresponding to vac

- Makefile
- cnsi-manager/config/manager/kustomization.yaml
- cnsi-portal/scripts/cloud-native-security-inspector-portal.yaml
- cnsi-portal/src/app/view/assements/risk-report-view/risk-report-view.component.ts
- cnsi-portal/src/app/view/policy/policy-setting-page/policy-setting-page.component.ts
- deployments/charts/cnsi/Chart.yaml
- deployments/charts/cnsi/values.yaml
- deployments/yaml/data-exporter.yaml
Modify version number 0.3.1 -> 0.3.2
> Modify the version number

- cnsi-manager/config/manager/manager.yaml
- deployments/yaml/manager.yaml
Fix build manger version using cnsi-manager/config/manager/kustomization.yaml change
> Fix build manger version using cnsi-manager/config/manager/kustomization.yaml change

- test/e2e/e2e_test.go
Fixes ISSUE #xxx
What will be the pain point if you don't make this change?
screenshots, console outputs or logs are acceptable.
screenshots, console outputs or logs are acceptable.
> Martinez ju patch 1

- Makefile
- cnsi-inspector/pkg/assets/workload/workload.go
- cnsi-inspector/pkg/image-scanner/controller.go
- cnsi-portal/src/app/view/assements/kube-bench-report-list/kube-bench-report-list.component.spec.ts
- cnsi-portal/src/app/view/assements/kube-bench-report-test-view/kube-bench-report-test-view.component.spec.ts
- cnsi-scanner-trivy/pkg/harbor/model.go
- cnsi-scanner-trivy/pkg/scan/controller.go
- cnsi-scanner-trivy/pkg/scan/transformer.go
- cnsi-scanner-trivy/pkg/trivy/model.go
- lib/http/client.go
Add a build-in scanner to get vulnerability info for workloads
> Fetch security data from build-in scanner

- cnsi-portal/src/app/route-strategy.service.ts
- cnsi-portal/src/app/view/assements/report-view-detail/report-view-detail.component.css
- cnsi-portal/src/app/view/assements/report-view-detail/report-view-detail.component.less
- cnsi-portal/src/app/view/assements/report-view/report-view.component.ts
- cnsi-portal/src/app/view/assements/risk-report-view/risk-report-view.component.ts
- cnsi-portal/src/app/view/data-source/vac/vac-setting/vac-setting.component.ts
- cnsi-portal/src/app/view/policy/policy.component.spec.ts
> Portal test related bug fixes

- cnsi-inspector/pkg/image-scanner/controller.go
- deployments/yaml/scanner-trivy.yaml
Resolve #253 
Test:
After fix:
> fix trivy issue

- cnsi-portal/package.json
- cnsi-portal/test/ui_unit.sh
> fix the security patch for UI

- cnsi-portal/node-server.js
- cnsi-portal/src/app/app-routing.module.ts
- cnsi-portal/src/app/app.module.ts
- cnsi-portal/src/app/components/nav/nav.component.html
- cnsi-portal/src/app/view/assements/pkgload-report-detail/pkgload-report-detail.component.css
- cnsi-portal/src/app/view/assements/pkgload-report-detail/pkgload-report-detail.component.html
- cnsi-portal/src/app/view/assements/pkgload-report-detail/pkgload-report-detail.component.less
- cnsi-portal/src/app/view/assements/pkgload-report-detail/pkgload-report-detail.component.spec.ts
- cnsi-portal/src/app/view/assements/pkgload-report-detail/pkgload-report-detail.component.ts
- cnsi-portal/src/app/view/assements/pkgload-report/pkgload-report.component.css
- cnsi-portal/src/app/view/assements/pkgload-report/pkgload-report.component.html
- cnsi-portal/src/app/view/assements/pkgload-report/pkgload-report.component.less
- cnsi-portal/src/app/view/assements/pkgload-report/pkgload-report.component.spec.ts
- cnsi-portal/src/app/view/assements/pkgload-report/pkgload-report.component.ts
- cnsi-portal/src/app/view/policy/policy-setting-page/policy-setting-page.component.ts
- cnsi-portal/src/assets/i18n/en.json
- cnsi-portal/src/assets/i18n/zh_CN.json
portal implements Pkgload Scanner configuration and data content display
> portal implements Pkgload Scanner configuration and data content display
